baseurl = "https://daniilidis-group.github.io/penncosyvio/"
languageCode = "en-us"
title = "PennCOSYVIO Data Set"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true

[params]
	# General information
	author = "Bernd Pfrommer"
	description = "A data set for Visual Inertial Odometry."

	# Repository
	provider = "GitHub"

	favicon = "upenn_favicon.jpg"

	permalink = "#"

	# Custom assets
	custom_css = ["tweaks.css"]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""
	logo = "upenn_favicon.jpg"

	[params.palette]
	    	primary = "blue"
    		accent  = "light-green"

	[params.font]
		text = "Ubuntu"
		code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "berndpfrommer"
	email   = "pfrommer@seas.upenn.edu"

[[menu.main]]
	name   = "Overview"
	url    = ""
	weight = 0

[[menu.main]]
	name   = "Download"
	url    = "download/"
	weight = 10
[[menu.main]]
	name   = "Intrinsic Calibration"
	url    = "intrinsic_calib/"
	weight = 20
[[menu.main]]
	name   = "Extrinsic Calibration"
	url    = "extrinsic_calib/"
	weight = 30


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
